### ISSUE TITLE
Serious problems with MDCollectionViewCell

### ISSUE THREAD

**Issue by Sergionius** [fpt-software/Material-Controls-For-iOS#1]
Hello, first of all thank you very much for your great job for transfer material controls.
I found serious problems with MDCollectionViewCell:
1. Does not call collectionView delegate - (void)collectionView:(UICollectionView *)collectionView didSelectItemAtIndexPath:(NSIndexPath *)indexPath
if i change my collectionViewCell superclass to MDCollectionViewCell.
2. If my collectionViewCell consists of an element which covers the entire space (such as a picture or view), the animation becomes invisible under this picture or view(view cover animation).

**Comment by Nvt2106** [comment]
Thank you so much for your effort to find those serious problems, Sergionius.
We are working to fix those problems and will push update soon.

**Comment by VuH-Uct** [comment]
@Sergionius : please try again with our latest commit, hope those problems are fixed!
