### ISSUE TITLE
When does this Material-Controls kit support iOS 10 OS? 

### ISSUE THREAD

**Issue by lokendrayadav** [fpt-software/Material-Controls-For-iOS#107]
We are using Material Control For Ios and recently Ios 10 launch so when it will start to support ios 10

**Comment by pxbachs** [comment]
You can checkout develop branch for latest code. I will update cocoapod soon. Thanks

**Comment by pxbachs** [comment]
Use: pod 'MaterialControls', '~> 1.2.0'
