### ISSUE TITLE
built with xcode8 got an error but it is ok with xcode7

### ISSUE THREAD

**Issue by yamingd** [fpt-software/Material-Controls-For-iOS#109]
Pods/MaterialControls/iOSUILib/iOSUILib/MDRippleLayer.m:131:24: No known instance method for selector 'mdLayer:didFinishEffect:'

**Comment by aMGLn** [comment]
https://github.com/fpt-software/Material-Controls-For-iOS/issues/94

**Comment by aMGLn** [comment]
#94

**Comment by pxbachs** [comment]
@yamingd  Plz checkout latest code. Thanks.
