### ISSUE TITLE
MDTabBarViewController orientation issue

### ISSUE THREAD

**Issue by shinurag** [fpt-software/Material-Controls-For-iOS#113]
Hello,
 
MDTabBarViewController landscape orientation not gives the proper UI for 'Indicator', Tried to implement a TabBarViewController with 3 Tabs. How to fix this orientation problem?

**Comment by shinurag** [comment]
Problem Solved by add a line `[self updateSegmentsList];` in between `[self resizeItems];` and `[self moveIndicatorToSelectedIndexWithAnimated:YES];` from the method `observeValueForKeyPath`.  **MDTabBar.m** file

**Comment by pxbachs** [comment]
Thanks @shinurag
