### ISSUE TITLE
MDRippleLayer/MDTouchGestureRecognizer prevents scrolling action from starting on a button

### ISSUE THREAD

**Issue by nesevis** [fpt-software/Material-Controls-For-iOS#13]
This is a particular problem inside a scrollview that has multiple buttons.

**Comment by Nvt2106** [comment]
Thanks nesevis for this finding, we are looking at it to find solution

**Comment by nesevis** [comment]
Cheers!

**Comment by NorbertSzydlowski** [comment]
Update cocoapods?
