### ISSUE TITLE
Xamarin: MDProgress linear type showing both linear and circular

### ISSUE THREAD

**Issue by nmilcoff** [fpt-software/Material-Controls-For-iOS#132]
Hi everyone! Thank you for this awesome library / binding for Xamarin.

I'm trying to add a MDProgress programatically but I can't find a way to display just a linear one. I'm using the following config:

```
var indeterminateProgress = new MDProgress();
indeterminateProgress.ProgressStyle = MDProgressStyle.Linear;
indeterminateProgressProgressType = MDProgressType.Indeterminate;

View.AddSubview(indeterminateProgress);

//
... constraints here
//
```

The expected behavior would be to have a linear indeterminate progress, but the current result is a linear and a circular progress both showing in the screen.

**Comment by fedemkr** [comment]
Hi, I've been struggling with this too and can't get to display just a linear one.

**Comment by progress44** [comment]
Hi, try this fix https://github.com/fpt-software/Material-Controls-For-iOS/pull/139

**Comment by nmilcoff** [comment]
Since I'm having the issue with the Xamarin Binding version of the library, I would need a compiled version of the code and then make the binding compile again. I will do it this asap and come back with an answer. Thanks!

**Comment by nmilcoff** [comment]
Hi @progress44 I'm not really able to test your fix. I am a Xamarin developer, would it be possible to ask you to update the [.a file](https://github.com/fpt-software/Material-Controls-For-iOS/blob/master/MaterialControls.Xamarin.Binding/libMaterialControls.a)? After that I can test / modify the Xamarin binding project.

**Comment by progress44** [comment]
Hi @nmilcoff, this is the library file with the fix.
 https://github.com/caffeinalab/ti.material/blob/master/iphone/libMaterialControls.a 
Let me know

**Comment by nmilcoff** [comment]
Thank you @progress44! I updated the lib and the issue is gone 💯
