### ISSUE TITLE
Issues with Xcode 7 and MDTextField

### ISSUE THREAD

**Issue by jyounus** [fpt-software/Material-Controls-For-iOS#14]
Hey there,

I've added this to my pods file, to make sure I'm testing with the very latest commit of yours: 
```pod 'MaterialControls', :git => 'https://github.com/fpt-software/Material-Controls-For-iOS.git', :commit => 'f5f91834ab'```

I'm trying to use the MDTextField on a simple UIView via Storyboard, however the IBDesignable keeps crashing for me. I keep getting the following error message:

```file:///Users/jayy/Documents/Xcode/Test/Test/Base.lproj/Main.storyboard: error: IB Designables: Failed to update auto layout status: The agent raised a "NSInvalidArgumentException" exception: Unable to parse constraint format: 
Unable to interpret '|' character, because the related view doesn't have a superview 
H:|-0-[view]-0-| 
            ^```


I'm have a brand new UIViewController with a label, a button and the MDTextField UIView dragged out. When I try to run it in the simulator, it crashes straight away.

Any ideas what the issue is?

**Comment by 99centsappdevelopment** [comment]
I have the same problem

**Comment by jeryRazakarison** [comment]
Same here.
When debugging the custom view, MDDeviceHelper.m l36
```
if (window == nil)
          window = [[[UIApplication sharedApplication] delegate] window];//#14
```
window is nil

**Comment by Gagan-tuffgeekers** [comment]
Facing the same
