### ISSUE TITLE
I can't pull via pod 

### ISSUE THREAD

**Issue by PWDream** [fpt-software/Material-Controls-For-iOS#2]
Thank you very much,I can't pull via pod ,please tell me why?
Tip me "[!] Unable to find a specification for `MaterialControls (~> 1.0.2)`"

**Comment by Nvt2106** [comment]
Many thanks for your effort to trying this library. We are investigating your issue.

**Comment by VuH-Uct** [comment]
Hi PWDream, could you run 'pod install --verbose' and show me the console log?

**Comment by PWDream** [comment]
OK，this is log:
Resolving dependencies of `Podfile`
Finished resolution (0 steps) (Took 1.101442 seconds) (2015-07-30 13:21:04 +0800)
[!] Unable to find a specification for `MaterialControls (~> 1.0.2)`

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/resolver.rb:395:in `handle_resolver_error'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/resolver.rb:64:in `rescue in resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/resolver.rb:55:in `resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:440:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:438:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:63:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:196:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:114:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:113:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:93:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.2/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'

**Comment by Nvt2106** [comment]
Hi PWDream, thanks for your log, but sorry that we still can't reproduce your issue.

Could you please try to run following commands:
$ pod repo remove master
$ pod setup
$ pod install

**Comment by PWDream** [comment]
Thank you ,I can't install via last method,but I install used 
pod 'MaterialControls', :git =>'https://github.com/fpt-software/Material-Controls-For-iOS.git'
method,please tell me why?

**Comment by PWDream** [comment]
I want to ask question:why I use tableViewCell Page is not smooth when I data very much?
why?

**Comment by VuH-Uct** [comment]
It happens when your cell has a lot of sub-views or images. You can get some advices from these links:
http://stackoverflow.com/a/21298399
http://iosinjordan.tumblr.com/post/56778173518/help-my-tables-dont-scroll-smoothly
