### ISSUE TITLE
Swift cant use MDTextField,MDSlider but MDButton goes well

### ISSUE THREAD

**Issue by havyre** [fpt-software/Material-Controls-For-iOS#24]
I use Swift with a Header.h file of #import "MDTextfiel.h",but I cant use MDTextField

let frame = CGRectMake(....)
let a =  MDTextField(frame:frame)
self.view.addSubView(a)

code runs well,but I cannt see any TextField on the screen even I setted backgroundColor

**Comment by VuH-Uct** [comment]
Hi @havyre !
**MDTextField** and **MDSlider** only work with Auto Layout. So you need to use constraints instead of frame to positioning and resizing the views.
