### ISSUE TITLE
crash when select a date

### ISSUE THREAD

**Issue by havyre** [fpt-software/Material-Controls-For-iOS#26]
MDCalendarDateHeader.m line 273 says " monthName = [monthName substringToIndex:3];"
it make crash ,I change it to  " monthName = [monthName substringToIndex:2];" , now runs well

**Comment by havyre** [comment]
sorry ,it is line 236 actually

**Comment by VuH-Uct** [comment]
It seems like you used the old version of MDCalendarDateHeader.m. We've already fixed this error about three months ago. Please get the latest code and try again. Thanks!
