### ISSUE TITLE
MDTabBar with transparent text has incorrect color

### ISSUE THREAD

**Issue by xinsight** [fpt-software/Material-Controls-For-iOS#33]
When an item in `MDTabBar` is not selected, it uses a white colour with 0.6 opacity. However, the end result, is not the background color but the a grey color.

<img width="388" alt="transparent-text-grey" src="https://cloud.githubusercontent.com/assets/465971/11506749/e4c16c04-981e-11e5-8c70-58d39ebf49ab.png">

Expected:

<img width="389" alt="transparent-text-expected" src="https://cloud.githubusercontent.com/assets/465971/11506754/ea455b86-981e-11e5-816b-975459a937fc.png">

This seems to be caused by the `MDRippleLayer` - if the ripple layer is not created, then the text color blends with the background color correctly. Any ideas how to fix?

**Comment by VuH-Uct** [comment]
Thank @xinsight , I'll try to find out what's wrong here.

**Comment by VuH-Uct** [comment]
I've fixed this issue on 62bd74d28fb1f5a59073a7a64f3dbdf74e963370 commit. It's caused by MDRippleLayer's shadow color.
