### ISSUE TITLE
tabBarViewController?.tabBar.selectedIndex does not move to corresponding content

### ISSUE THREAD

**Issue by sohayb** [fpt-software/Material-Controls-For-iOS#40]
I want to initialise the view controller with initial index (let's say index 3 out of the 5 existing tabs), the tabbar moves to the right index, but not the content. I get the content of the first tab under the 3 tab.
Not sure if it's a bug or I'm missing something.

**Comment by VuH-Uct** [comment]
Hi @sohayb , I've update the MDTabBarViewController. Now you can use MDTabBarViewController.selectedIndex to change the content index.

**Comment by sohayb** [comment]
Thanks! I assume that's not pushed to CocoaPods right? will try that later today

**Comment by sohayb** [comment]
Never mind, I changed the pod import to this:
````
pod 'MaterialControls',:git => 'https://github.com/fpt-software/Material-Controls-For-iOS.git'
````
And all is working great now! Thanks :+1:
