### ISSUE TITLE
MDTextFiled missing bottom divider

### ISSUE THREAD

**Issue by sohayb** [fpt-software/Material-Controls-For-iOS#43]
I'm having a strange issue where the MDTextFiled doesn't have the bottom separator!
<img width="327" alt="screen shot 2015-12-18 at 12 08 26 am" src="https://cloud.githubusercontent.com/assets/2195533/11883492/09144978-a51c-11e5-8f45-119ba61011a5.png">
The properties of the view are the following:
<img width="265" alt="screen shot 2015-12-18 at 12 13 00 am" src="https://cloud.githubusercontent.com/assets/2195533/11883503/244787c8-a51c-11e5-94fe-97061c5d3e21.png">
I didn't modify anything by code. Can you please help with this.Thanks!

**Comment by VuH-Uct** [comment]
Did you set height constraint for the textfield?

**Comment by sohayb** [comment]
I set it to 55 and now I have this:
<img width="364" alt="screen shot 2015-12-18 at 3 23 05 pm" src="https://cloud.githubusercontent.com/assets/2195533/11897790/577d6b4c-a59b-11e5-8018-3fe87aab1e3d.png">
Setting it to any larger value won't solve the problem, as the text is cut off:
<img width="301" alt="screen shot 2015-12-18 at 3 26 34 pm" src="https://cloud.githubusercontent.com/assets/2195533/11897851/c504abb2-a59b-11e5-84a7-5a19c1d281a3.png">

**Comment by VuH-Uct** [comment]
@sohayb , did you fix this issue?

**Comment by sohayb** [comment]
After changing some layout conditions, it was fixed, or at least I thought it was but apparently it didn't, as other layout constraints got messed up but forgot to reopen it, sorry about that. I now reverted back to using the normal TextField till I figure out what to do.

**Comment by VuH-Uct** [comment]
You do not need to (and should not) set the height constraint for MDTextView. MDTextView automatically changes its height base on its contents, using its own constraints.

**Comment by nesevis** [comment]
I'm using the MDTextView programmatically, so I wrapped it in a UIView that I can set the dimensions of. Having the MDTextView then fit itself to those constraints, it works well at about a height of ~75 (including the error field below the line).

**Comment by VuH-Uct** [comment]
With 18d533aae728099556d37767ca54fd8d02525ff1, now the MDTextView will show correctly even with fixed frame. Please try and let me know if you have any issue
