### ISSUE TITLE
MDTabBar with Images not showing

### ISSUE THREAD

**Issue by sohayb** [fpt-software/Material-Controls-For-iOS#45]
I added the MDTabBar from StoryBoard and then inside the controller I had this:
````
let images:[UIImage!] = [UIImage(named: "ic_filter_list_white"), UIImage(named: "ic_sort_white")]
tabBar.setItems(names)
````
The tabs are being added but the images just aren't showing.
Anything I'm doing wrong or am I missing something? Thanks!

**Comment by jackcook** [comment]
I am having the same issue, thanks

**Comment by sohayb** [comment]
It seems like something related to the holding UISegmentedControl, solved the issue by doing this:
```swift
        var imageOne = UIImage(named: "ic_filter_list_white_36dp")
        imageOne = imageOne?.imageWithRenderingMode(.AlwaysOriginal)
        
        var imageTwo = UIImage(named: "ic_sort_white_36dp")
        imageTwo = imageTwo?.imageWithRenderingMode(.AlwaysOriginal)
        let names:[UIImage!] = [imageOne, imageTwo]
        tabBar.setItems(names)
```
Got the fix from this [SO answer] (http://stackoverflow.com/a/18915697/1351433)
