### ISSUE TITLE
Demo not running

### ISSUE THREAD

**Issue by nicgutierrez** [fpt-software/Material-Controls-For-iOS#5]
Thanks for the library, looks promising.

I wasn't able to compile the application because of some errors:

* file:///Users/nic/Desktop/Material-Controls-For-iOS-master/iOSUILibDemo/Base.lproj/Main.storyboard: error: IB Designables: Failed to update auto layout status: Failed to load designables from path (null)
* /Users/nic/Desktop/Material-Controls-For-iOS-master/iOSUILibDemo/DatePickerViewController.m:31:1: Illegal redeclaration of property in class extension 'DatePickerViewController' (attribute must be 'readwrite', while its primary must be 'readonly')

I'm using Xcode Version 6.4 (6E35b).

Hope this helps.

**Comment by VuH-Uct** [comment]
Hi Nicgutierrez! 
Thank for your report, and we fixed this issue, hope you can compile it now.

**Comment by nicgutierrez** [comment]
Awesome!

Thank you @VuH-Uct :)
