### ISSUE TITLE
Swift how-to-use

### ISSUE THREAD

**Issue by rafaeliga** [fpt-software/Material-Controls-For-iOS#63]
Hi,

What are the steps to use the library on Swift?

I installed using CocoaPods, Podfile:

pod 'MaterialControls', '~> 1.0.2'

I've added, on my "Bridging-Header":

#import "MaterialControls/MDTableViewCell.h"

and then Im trying to use on my swift class:

`class` BlogTableViewCell: MDTableViewCell {``

and I got an error saying that cant find the class:

<img width="897" alt="blogtableviewcell_swift" src="https://cloud.githubusercontent.com/assets/92042/13725864/88777ed8-e88d-11e5-9ff8-6ac63b53826f.png">

Is that right? What am I missing?

Thanks,

**Comment by zishanj** [comment]
I have just  included this line

`import MaterialControls`

and build the project CMD + B. It then updated all the references.

**Comment by rafaeliga** [comment]
@zishanj thanks, but did you included something in the Objective-C bridging header?
Are you using the cocoapods to install?

**Comment by zishanj** [comment]
Yes, I am using cocoapods. Here is what my pod file looks like:

```
use_frameworks!
pod 'MaterialControls', :git => 'https://github.com/fpt-software/Material-Controls-For-iOS.git'
```

Here, instead of using any version, I am directly using the Master repository to keep upto date. Then I just used `import MaterialControls` in my swift file and Build the project to update all references.

**Comment by rafaeliga** [comment]
@zishanj it works! thank you very much.
No need imports on Objective-C bridging header.
I think this should be added to the README :D
