### ISSUE TITLE
how to set the size of MDProgress in Circular form?

### ISSUE THREAD

**Issue by terminatorlkf** [fpt-software/Material-Controls-For-iOS#66]
it seems that the size of MDProgress in Circular form is constant and I don't know how to change it

**Comment by VuH-Uct** [comment]
You can change its size by call [MDProgress setCircularSize:]

**Comment by terminatorlkf** [comment]
@VuH-Uct It doesn't work. Xcode says no visible @interface for "MDProgress" declares the selector 'setCircularSize:'

**Comment by VuH-Uct** [comment]
Which version of the library are you using? This property has been added from 2f9e604b0452701de105cb4f211edccfdf5a194a commit.

**Comment by terminatorlkf** [comment]
@VuH-Uct Thanks!!!!!!!! You solved my problem perfectly

**Comment by VuH-Uct** [comment]
You're welcome!
