### ISSUE TITLE
Add a way to display MDSnackbar above navigation controller toolbar

### ISSUE THREAD

**Issue by eytanbiala** [fpt-software/Material-Controls-For-iOS#7]
Currently the MDSnackbar only shows from the bottom of the current view controller.
When the view controller has a bottom toolbar, the snackbar covers the toolbar.
It would be nice to have a way to show the snackbar above the toolbar, so it does not cover the toolbar at all.

**Comment by eytanbiala** [comment]
Thanks for addressing this!

**Comment by Nvt2106** [comment]
You are welcome, eytanbiala!
