### ISSUE TITLE
Please publish library target for XCode project

### ISSUE THREAD

**Issue by SmartyP** [fpt-software/Material-Controls-For-iOS#78]
I'm trying to build the .a file myself, but having no luck. I setup a new target that includes all the .m files in Compile Sources, and includes the .h files and the .ttf files in Copy Files. I built the simulator and device .a files and merged them with lipo. I'm ending up with a .a file that is 6.1mb instead of 9.7mb, and running the sample against it runs, but doesn't render anything.

Could you include the target for generating the .a file from the source, or instructions on building it manually?

Thanks for the consideration!

**Comment by pxbachs** [comment]
Plz checkout latest code. You can build your own .a file by using Makefile in MaterialControls folder.
