### ISSUE TITLE
Xamarin binding project is incomplete

### ISSUE THREAD

**Issue by SmartyP** [fpt-software/Material-Controls-For-iOS#79]
The Xamarin binding project currently posted does not include the binding definitions for MDTabBarViewController and other controls found in the library in the ApiDefinition.cs. However, the library installed via Nuget or Xamarin Components does include those controls. Could you please post the complete bindings for the library as used for the component?

**Comment by pxbachs** [comment]
You can checkout latest code, I added binding and sample projects. Plz let me know if it has issues. Thanks.
