### ISSUE TITLE
Way to dismiss/hide tabBar in MDTabBarViewController?

### ISSUE THREAD

**Issue by dgkatz** [fpt-software/Material-Controls-For-iOS#9]
I am looking for a way to "dismiss" or "hide" the tabBar in MDTabBarViewController.
I would like the tabBar to be dismissed when I scroll a tableview. 
I have tried updating the frame of the tabBar by saying 
tabBarViewController.tabBar.frame = newFrame;
This does not work, the tabBar's position does not change.
Is there a different way, something I missed?

**Comment by VuH-Uct** [comment]
We used Auto Layout in MDTabBarViewController, so that you cannot change tabBar's frame directly, you need to change tabBar's constraints. 
I think you need to change some lines of code in MDTabBarViewController's addConstraints function to get the constraint you want.

**Comment by dgkatz** [comment]
Worked like a charm, thank you!

**Comment by samiq** [comment]
@dgkatz any chance you could share the code on how you were able to make it work, I'm trying to do the same. appreciate if could share. you can email me to gcorrales@gmail.com

**Comment by dgkatz** [comment]
I realized my solution did not work, this question should be reopened.
