### ISSUE TITLE
XCode 8 beta 3 No known instance method for selector 'mdLayer:didFinishEffect:'

### ISSUE THREAD

**Issue by PWDream** [fpt-software/Material-Controls-For-iOS#94]
I use pod manager the project,but the project have a error in XCode 8 beta 3 No known instance method for selector 'mdLayer:didFinishEffect:'.Can you help me? Thank you.

**Comment by freakmoder** [comment]
experienced the same behaviour here

**Comment by NeilNie** [comment]
I have the same issue as well. Here is my fix for this problem. 
`
@protocol MDLayerDelegate <NSObject>
@optional
- (void)mdLayer:(MDRippleLayer *)layer didFinishEffect:(CFTimeInterval)duration;
@end`
Then create delegate in the .h file
`@property (nullable, assign) id delegate;`

In the .m file:
`- (void)animationDidStop:(CAAnimation *)anim finished:(BOOL)flag {
  if (anim == [self animationForKey:@"opacityAnim"]) {
    self.opacity = 0;
  } else if (flag) {
    if (_userIsHolding) {
      _effectIsRunning = false;
      if (self.delegate) {
        [self.delegate mdLayer:self didFinishEffect:anim.duration];
      }
    } else {
      [self clearEffects];
    }
  }
}`

**Comment by jlaws** [comment]
This is cleaner than @NeilNie's fix.

Update line 135 of MDRippleLayer.m

if ([self.delegate conformsToProtocol:@protocol(MDLayerDelegate)] &&
     [self.delegate respondsToSelector:@selector(mdLayer:didFinishEffect:)]) {
        id<MDLayerDelegate> delegate = (id<MDLayerDelegate>)self.delegate;
        [delegate mdLayer:self didFinishEffect:anim.duration];
      }

**Comment by amphora-ken** [comment]
Since the method is optional, checking conformance doesn't help.  Here's my approach:

      if (self.delegate && [self.delegate respondsToSelector:@selector(mdLayer:didFinishEffect:)]) {
            [(id<MDLayerDelegate>) self.delegate mdLayer:self didFinishEffect:anim.duration];
      }

**Comment by ernesto** [comment]
Using pod 'MaterialControls' the issue persist. How fix?

**Comment by pxbachs** [comment]
Thanks all. Plz checkout latest code.
